spring.application.name=cloudvault


# Aiven MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# =========================================================
# JWT Authentication
# =========================================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# =========================================================
# JPA / Hibernate
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# =========================================================
# Backblaze B2 Object Storage
# =========================================================

b2.endpoint=https://s3.us-east-005.backblazeb2.com
b2.bucket-name=cloudvault-files-project
b2.access-key=${B2_ACCESS_KEY}
b2.secret-key=${B2_SECRET_KEY}


# =========================================================
# File Upload Limits
# =========================================================

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# =========================================================
# Google OAuth 2.0
# =========================================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# =========================================================
# Frontend URL
# =========================================================
app.frontend-url=${FRONTEND_URL:http://localhost:5173}